// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyqeyxgimvwooegpaapp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55cWV5eGdpbXZ3b29lZ3BhYXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NjE2MzEsImV4cCI6MjA1NDIzNzYzMX0.MaFplMd-58LvxChNsaGuznSslIzJ1OulASEvRt5ZmqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);